### ISSUE TITLE
Display checklist on Dodona

### ISSUE THREAD

**Issue by stijndcl** [dodona-edu/judge-html#21]
The test suite is good enough to create the checklist, now we should loop through it and show it on Dodona somehow.

- [x] Show successful tests
- [x] Show failed tests
- [x] Show validation warnings (accessible via the suite!)
- [x] Show correct/failed if all tests succeeded
